### ISSUE TITLE
Electron Environment?

### ISSUE THREAD

**Issue by jnovack** [ebshimizu/hots-parser#3]
I'd like to silence the logging by default.

Use Case:

* When this runs in Electron, I believe all the logging lines are necessary to track progress, or even prove it's working.
* When this runs as a FaaS, I don't believe all the lines are necessary all the time, and printing to the console DOES delay processing (I'm trying to shave milliseconds).

I'll happily rewrite the logging, are you amenable to at least setting an environment variable when you want logs?

**Comment by ebshimizu** [comment]
The logging is mostly just there for debugging as I was developing the app. There's no particular reason to keep them in for production settings until an error occurs (even in my app).

My preference would be to set logging as an option in the `opts` argument to the parse function. A script calling the function could use an environment var to auto-set that argument to `off` or whatever the lowest log setting happens to be.

**Comment by jnovack** [comment]
I was just going to use [pino](http://getpino.io/#/) unless you had preference for something else.  It supports logging objects for tracing or debugging.

```
$ cat test.js
const pino = require('pino');
const pretty = pino.pretty({forceColor: true})
pretty.pipe(process.stdout);
var log = pino({
  name: 'app',
  safe: true,
  level: 'trace'
}, pretty)

log.info('hello world')
log.error('this is at error level')
log.fatal('the answer is %d', 42)
log.warn({ obj: 42 }, 'hello world')
log.debug({ obj: 42, b: 2 }, 'hello world')
log.trace({ obj: { aa: 'bbb' } }, 'another');

$ node test.js
[2018-07-23T18:19:40.986Z] INFO (app/89847 on jnovack-macpro): hello world
[2018-07-23T18:19:40.990Z] ERROR (app/89847 on jnovack-macpro): this is at error level
[2018-07-23T18:19:40.991Z] FATAL (app/89847 on jnovack-macpro): the answer is 42
[2018-07-23T18:19:40.991Z] WARN (app/89847 on jnovack-macpro): hello world
    obj: 42
[2018-07-23T18:19:40.991Z] DEBUG (app/89847 on jnovack-macpro): hello world
    obj: 42
    b: 2
[2018-07-23T18:19:40.991Z] TRACE (app/89847 on jnovack-macpro): another
    obj: {
      "aa": "bbb"
    }
```
(it has color in the console)

**Comment by ebshimizu** [comment]
no objections here 👍 . It supports browser-level output, which is how I usually end up debugging it in electron.
