### ISSUE TITLE
Hogger undefined after parsing a replay

### ISSUE THREAD

**Issue by patonz** [ebshimizu/hots-parser#55]

**Comment by ebshimizu** [comment]
thanks for the report, but I'm going to need a bit more information that that. Is there a replay you can link that has this issue?

**Comment by patonz** [comment]
this is the link of .StormReplay

[WeTransfer- Storm Replay](https://we.tl/t-mWxeujLUhO)

**Comment by ebshimizu** [comment]
thanks! I'll take a look

**Comment by ebshimizu** [comment]
hmm I'm unable to replicate Hogger being undefined for this replay. It displays Hogger in the match data without issue in Stats of the Storm v2.6.41, which uses hots-parser v7.53.5.

The only issue I can think of that would cause this is a version mis-match, so check that the parser is up to date and that the most recent hero-protocol library has been downloaded.

**Comment by patonz** [comment]
ok in order to fix this "issue", i had to indicate "heroprotocol": "github:GaryIrick/heroprotocol", on my package.json
Strange behavior bacause is on your dependencies already, so has been installed automatically. 
Dunno but now it works.

**Comment by ebshimizu** [comment]
ah yeah that was a switch a while back to provide a fall-through in the event that heroprotocol wasn't up to date. Unsure why it needed to be explicitly set, as the `hots-parser` module has a dependency locked to that version.
