### ISSUE TITLE
Valid Key Names in JSON

### ISSUE THREAD

**Issue by jnovack** [ebshimizu/hots-parser#6]
Valid key names in JSON [SHOULD NOT](https://www.ietf.org/rfc/rfc2119.txt) contain spaces.

So sayeth the Google...

> Property names must conform to the following guidelines:
> 
> * Property names should be meaningful names with defined semantics.
> * Property names must be camel-cased, ascii strings.
> * The first character must be a letter, an underscore (_) or a dollar sign ($).
> * Subsequent characters can be a letter, a digit, an underscore, or a dollar sign.
> * Reserved JavaScript keywords should be avoided (A list of reserved JavaScript keywords can be found below).
> 
> These guidelines mirror the guidelines for naming JavaScript identifiers. This allows JavaScript clients to access properties using dot notation. (for example, `result.thisIsAnInstanceVariable`). Here's an example of an object with one property:
> 
> ```
> {
>   "thisPropertyIsAnIdentifier": "identifier value"
> }
> ```

References:
*  https://google.github.io/styleguide/jsoncstyleguide.xml#Property_Name_Format

Violations:

1. `players.HERO-ID` - Contains `-`, requires quoting
1.1 `players.` can be an array, in the same order as `match.playerIDs` as the object already contains the `.ToonHandle`.
2. `players.HERO-ID.talents.Tier X Choice` - Contains ` ` (spaces), requires quoting.
2.1 No ~~capes~~ spaces!  Just like `players.HERO-ID.gameStats.TierXTalent` does not need spaces.

```
$ cat towers-of-doom.json | jq '.players."1-Hero-1-5685494".talents'
{
  "Tier 1 Choice": "AlarakRuthlessMomentum",
  "Tier 2 Choice": "AlarakChaosReigns",
  "Tier 3 Choice": "AlarakDissonance",
  "Tier 4 Choice": "AlarakHeroicAbilityCounterStrike",
  "Tier 5 Choice": "AlarakBladeoftheHighlord",
  "Tier 6 Choice": "AlarakLethalOnslaughtDiscordStrike"
}
```

This is a breaking change.

**Comment by ebshimizu** [comment]
2 was pulled directly from the keys in the replay files. It can be fixed pretty easily: https://github.com/ebshimizu/hots-parser/blob/399dec5024bb906c95739522d0c4279ad4bcd5d3/parser.js#L620 with a replacement to remove spaces. My app will just check for either key I think, not a huge deal.

Players can be converted to an array at the end of processing (optional in my opinion, depends on the application if it would like an object or array).
